### ISSUE TITLE
Grunt-Shopify runs twice?

### ISSUE THREAD

**Issue by terkelg** [wilr/grunt-shopify#16]
I have the following setup: A folder named src with all my sass, images, template etc. organized in subdirectories.  I use `grunt-contrib-copy`, `grunt-watch` and `grunt-newer` to “compile” this into a valid Shopify theme structure.  `Grunt-newer` is used to only copy changed files. Let’s say I edit and save my theme.liquid in my src folder, I get the following response:

![screen shot 2013-09-21 at 14 21 10](https://f.cloud.github.com/assets/2302254/1185610/96479ca2-22b8-11e3-947c-df34aba6cd68.png)

It looks like the grunt-shopify run twice. I tried to debug, but with no luck.
I tried to add a delay to `grunt-shopify`, but the same thing happens.

I guess `grunt-shopify` watch and looks for changes, and react immediately, before the file is done being copied with `grunt-contrib-copy`. I tried setting different options in watch like `options.spawn` and `options.debounceDelay`, but with no luck.

Both `grunt-shopify` and `grunt-contrib-copy` looks for changes in the app folder, but is it possible to somehow control the order in which they run?

My current watch setup:

``` javascript
watch: {
  copy: {
    files: '<%= project.src %>/**',
    tasks: ['newer:copy:shopify']
  },
  shopify: {
    files: ["app/**"],
    tasks: ["shopify"]
  }
}
```

Could it be that `grunt-contrib-copy` touches the files twice, and thereby trigger `shopify-grunt` twice?

In the end the file get’s uploaded and everything works fine, but the error really annoy me. And I can’t figure out why this happens.
##

**Comment by wilr** [comment]
Should now be resolved.
