### ISSUE TITLE
shopify watch errors

### ISSUE THREAD

**Issue by turbometalskater** [wilr/grunt-shopify#51]
According to the shopify [docs](https://docs.shopify.com/api/introduction/api-call-limit) there is a call limit to the shopify API, causing some errors when grunt watching with this task and at the same time executing something like `touch snippets/*` for uploading a set of liquid files.

For this reason I forked this repository ([link to the fork](https://github.com/turbometalskater/grunt-shopify)) and added some changes:
I've added a [queue](https://github.com/caolan/async#queue) from the [caolan/async](https://github.com/caolan/async) module with a concurrency of value 1 (only one upload at the same time) and a configurable delay between API requests (Shopify docs hinting is on 2 calls per second, so ~500ms delay in the best case).
This works now only on the watched files.

The purpose is to extend this to all the other interested pieces of code, but I'm pretty new to nodejs programming, and also insecure of this project guidelines.
It will be beautiful having feedback on my commits, and how to proceed if this enhancement can be useful :)
##

**Comment by wilr** [comment]
Hi @turbometalskater, sounds like good changes. As long as it's configurable happy to merge in your changes. I'd recommend squashing your commits, add documentation to the readme and submit a PR for me to confirm and merge.

**Comment by wilr** [comment]
`rate_limit_delay` has been added as an option in the current release.
