### ISSUE TITLE
Shopify:Download grunt task not working

### ISSUE THREAD

**Issue by ghost** [wilr/grunt-shopify#54]
I was following this link to setup shopify theme locally on windows https://www.otreva.com/web-development/shopify-desktop-theme-editor-windows-linux/. 

Whenever i run shopify:download command some of the theme files  get downloaded and later it throws this error -> Assertion failed: end <= source_len, file src\smalloc.cc, line 280 and the task stops executing. Can someone please help me with it
##

**Comment by wilr** [comment]
Closing this issue. Please try the latest release and re-open with any error message
