### ISSUE TITLE
not in base path

### ISSUE THREAD

**Issue by williameliel** [wilr/grunt-shopify#61]
Got this issue today in a new mac I started using. No matter which shopify I try to run, I get a "not in base  path" error. It's really weird because the file IS in the base path.
For instance, when trying to do an upload or sync, or even when watching the files:

```
Running "shopify:sync" task
>> [grunt-shopify] - File "/XXX/assets/ajax-cart.js.liquid" not in base path
.
.
.
```
##

**Comment by wilr** [comment]
Hi @williameliel sorry for the delay getting back to you. Please try latest 1.0.0 release and post your config if this is still causing you trouble.

**Comment by williameliel** [comment]
thanks, will do!
