### ISSUE TITLE
watch stopped working shopify:upload still works

### ISSUE THREAD

**Issue by kevinmpowell** [wilr/grunt-shopify#62]
I used the watch method to upload only the files that have changed. I don't know what happened, but it stopped working overnight. `shopify:upload` still works. 

I didn't change anything on my end, so I'm wondering if Shopify changed something on their end.

I'm getting this line in my console:
`>> [grunt-shopify] - Uploading "assets/myfile.css"`

but I never get the:
`>> [grunt-shopify] - File "assets/myfile" uploaded`
unless I use `shopify:upload`

Obviously this is a huge issue since I don't want to have to manually upload every single one of my theme files when I make a change to one of them.
##

**Comment by gapipro** [comment]
Same issue here.

**Comment by wilr** [comment]
Tested latest and works, please re-open if you can still reproduce.
