### ISSUE TITLE
New 'Sections' feature in themes

### ISSUE THREAD

**Issue by emmadolan** [wilr/grunt-shopify#66]
Is there anyway to make this work with new themes that use 'Sections'? Get an error message using Grunt saying 'sections/collection.liquid not allowed by Shopify Whitelist'. Thanks.

**Comment by wilr** [comment]
@emmadolan thanks for using grunt-shopify. Have you got the latest version? This should be a whitelisted folder - https://github.com/wilr/grunt-shopify/blob/master/tasks/lib/shopify.js#L159-L168

**Comment by sreckosmodis** [comment]
@wilr there is a upload pattern missing here: 
https://github.com/wilr/grunt-shopify/blob/master/tasks/lib/shopify.js#L81
Can you add 'sections/\*.\*' to it?
I can also create a PR for this, but might be easier, if you just add it.

Thanks!
