### ISSUE TITLE
Suggestion: Ignore settings_data.json setting

### ISSUE THREAD

**Issue by QuintinS** [wilr/grunt-shopify#67]
A suggestion: A setting in the gruntfile that ignores the settings_data.json and doesn't upload it to the site if changes to it are detected.

I see there is an option for this on the upload command, but don't see a similar setting for the watch command.

**Comment by wilr** [comment]
You can use the `upload_patterns` filter to exclude this. Haven't tested it myself but using globbing patterns in grunt you can exclude the file.
```
upload_patterns: ['assets/*.*','config/*.*','layout/*.*','locales/*.*','snippets/*.*','templates/*.*','templates/customers/*.*', '!settings_data.json']
```

Let me know if that doesn't work any I'll set a flag but I'd prefer this approach.
