### ISSUE TITLE
"Loading "shopify.js" tasks...ERROR" after updating to 1.0.1 from 1.0.0

### ISSUE THREAD

**Issue by QuintinS** [wilr/grunt-shopify#69]
After updating to the latest version, I receive this error when running a watch tasks with `grunt-shopify@1.0.1`:

`Loading "shopify.js" tasks...ERROR`

Rolling back to 1.0.0 fixed this issue.

`
"devDependencies": {
    "glob": "~3.2.3",
    "growl": "^1.7.0",
    "grunt": "^1.0.1",
    "grunt-contrib-jshint": "^1.1.0",
    "grunt-contrib-nodeunit": "^1.0.0",
    "grunt-contrib-uglify": "^3.0.1",
    "grunt-contrib-watch": "^1.0.0",
    "grunt-shopify": "^1.0.0"
  }
`

**Comment by wilr** [comment]
Try `1.0.2`. There was a syntax error that sneaked in.
